import '../class/DishComment.dart';

Map<String, List<DishComment>> commentsByDish = {
  "D001": [
    // Phở bò
    DishComment(
        "C001",
        "U001",
        "Nguyễn Văn An",
        "https://randomuser.me/api/portraits/men/1.jpg",
        "Nước dùng ngọt thanh, thịt bò mềm vừa phải. Hướng dẫn nấu nước dùng rất chi tiết!",
        "2024-03-20",
        "15",
        "1",
        "1"),
    DishComment(
        "C002",
        "U002",
        "Trần Thị Bình",
        "https://randomuser.me/api/portraits/women/1.jpg",
        "Mình đã làm theo công thức này và cả nhà khen ngon. Phở thơm, bánh không bị nát.",
        "2024-03-19",
        "12",
        "0",
        "1"),
  ],
  "D002": [
    // Bún chả
    DishComment(
        "C003",
        "U003",
        "Lê Văn Cường",
        "https://randomuser.me/api/portraits/men/2.jpg",
        "Cách ướp thịt chuẩn vị Hà Nội. Nướng xong thịt thơm lừng cả nhà.",
        "2024-03-18",
        "18",
        "1",
        "1"),
    DishComment(
        "C004",
        "U004",
        "Phạm Thị Dung",
        "https://randomuser.me/api/portraits/women/2.jpg",
        "Nước chấm đậm đà, cách pha rất dễ làm theo. Thịt nướng không bị cháy.",
        "2024-03-17",
        "14",
        "2",
        "1"),
  ],
  "D003": [
    // Cơm tấm sườn
    DishComment(
        "C005",
        "U005",
        "Hoàng Văn Em",
        "https://randomuser.me/api/portraits/men/3.jpg",
        "Sườn nướng mềm, thấm gia vị. Bì và chả trứng làm cũng rất ngon.",
        "2024-03-16",
        "20",
        "1",
        "1"),
    DishComment(
        "C006",
        "U006",
        "Mai Thị Phương",
        "https://randomuser.me/api/portraits/women/3.jpg",
        "Công thức nước mắm chuẩn vị quán cơm tấm Sài Gòn. Cách ướp sườn rất hay!",
        "2024-03-15",
        "16",
        "0",
        "1"),
  ],
  "D004": [
    // Bánh xèo
    DishComment(
        "C007",
        "U007",
        "Đặng Văn Giang",
        "https://randomuser.me/api/portraits/men/4.jpg",
        "Bánh xèo giòn rụm, nhân đầy đặn. Bột pha theo tỷ lệ này rất chuẩn.",
        "2024-03-14",
        "19",
        "1",
        "1"),
    DishComment(
        "C008",
        "U008",
        "Nguyễn Thu Hà",
        "https://randomuser.me/api/portraits/women/4.jpg",
        "Mẹo đổ bánh không bị dính chảo rất hữu ích. Nước chấm ngon đúng điệu!",
        "2024-03-13",
        "17",
        "2",
        "1"),
  ],
  "D005": [
    // Bún bò Huế
    DishComment(
        "C009",
        "U009",
        "Trần Văn Hùng",
        "https://randomuser.me/api/portraits/men/5.jpg",
        "Vị cay nồng đúng kiểu Huế. Màu nước dùng đẹp, mùi sả thơm nức.",
        "2024-03-12",
        "22",
        "1",
        "1"),
    DishComment(
        "C010",
        "U010",
        "Lê Kim Anh",
        "https://randomuser.me/api/portraits/women/5.jpg",
        "Hướng dẫn nấu nước dùng rất chi tiết. Giò heo mềm, không bị dai.",
        "2024-03-11",
        "16",
        "0",
        "1"),
  ],
  "D006": [
    // Cá kho tộ
    DishComment(
        "C011",
        "U011",
        "Phan Văn Khải",
        "https://randomuser.me/api/portraits/men/6.jpg",
        "Cá kho đúng kiểu truyền thống, không bị tanh. Nước kho sệt vừa phải.",
        "2024-03-10",
        "21",
        "2",
        "1"),
    DishComment(
        "C012",
        "U012",
        "Nguyễn Thị Lan",
        "https://randomuser.me/api/portraits/women/6.jpg",
        "Mẹo kho cá không bị nát rất hay. Thịt ba chỉ kho cùng thêm đậm đà.",
        "2024-03-09",
        "18",
        "1",
        "1"),
  ],
  "D007": [
    // Gỏi cuốn
    DishComment(
        "C013",
        "U013",
        "Vũ Đức Mạnh",
        "https://randomuser.me/api/portraits/men/7.jpg",
        "Gỏi cuốn tươi ngon, đầy đặn. Tôm thịt được ướp vừa miệng.",
        "2024-03-08",
        "20",
        "1",
        "1"),
    DishComment(
        "C014",
        "U014",
        "Trần Thị Ngọc",
        "https://randomuser.me/api/portraits/women/7.jpg",
        "Cách cuốn không bị rách bánh tráng. Nước chấm đậm đà, có độ sánh.",
        "2024-03-07",
        "15",
        "0",
        "1"),
  ],
  "D008": [
    // Mì Quảng
    DishComment(
        "C015",
        "U015",
        "Lê Văn Oanh",
        "https://randomuser.me/api/portraits/men/8.jpg",
        "Mì Quảng chuẩn vị miền Trung. Nước dùng sánh, thơm mùi củ nén.",
        "2024-03-06",
        "23",
        "2",
        "1"),
    DishComment(
        "C016",
        "U016",
        "Phạm Thu Phương",
        "https://randomuser.me/api/portraits/women/8.jpg",
        "Topping phong phú, đầy đặn. Cách nấu nước dùng rất chi tiết.",
        "2024-03-05",
        "19",
        "1",
        "1"),
  ],
  "D009": [
    // Cơm niêu
    DishComment(
        "C017",
        "U017",
        "Hoàng Văn Quân",
        "https://randomuser.me/api/portraits/men/9.jpg",
        "Cơm dẻo thơm, cháy vàng đều. Các món ăn kèm rất hợp.",
        "2024-03-04",
        "17",
        "1",
        "1"),
    DishComment(
        "C018",
        "U018",
        "Nguyễn Thị Quỳnh",
        "https://randomuser.me/api/portraits/women/9.jpg",
        "Mẹo nấu cơm trong nồi đất rất hay. Cá kho ăn kèm tuyệt vời.",
        "2024-03-03",
        "14",
        "0",
        "1"),
  ],
  "D010": [
    // Bánh mì thịt
    DishComment(
        "C019",
        "U019",
        "Trần Văn Sơn",
        "https://randomuser.me/api/portraits/men/10.jpg",
        "Cách làm patê ngon như ngoài hàng. Bánh mì giòn rụm.",
        "2024-03-02",
        "25",
        "2",
        "1"),
    DishComment(
        "C020",
        "U020",
        "Lê Thị Thảo",
        "https://randomuser.me/api/portraits/women/10.jpg",
        "Đồ chua giòn ngon, thịt nguội ướp vừa vị. Rất đầy đủ nguyên liệu.",
        "2024-03-01",
        "20",
        "1",
        "1"),
  ],
  "D011": [
    // Bún riêu
    DishComment(
        "C021",
        "U021",
        "Đỗ Văn Thắng",
        "https://randomuser.me/api/portraits/men/11.jpg",
        "Riêu cua đậm đà, nước dùng trong veo. Cách làm riêu rất chi tiết.",
        "2024-02-29",
        "21",
        "1",
        "1"),
    DishComment(
        "C022",
        "U022",
        "Phạm Thị Uyên",
        "https://randomuser.me/api/portraits/women/11.jpg",
        "Đậu phụ chiên vàng giòn, rau sống tươi ngon. Hướng dẫn rất dễ làm theo.",
        "2024-02-28",
        "18",
        "0",
        "1"),
  ],
  "D012": [
    // Chả cá Lã Vọng
    DishComment(
        "C023",
        "U023",
        "Nguyễn Văn Vương",
        "https://randomuser.me/api/portraits/men/12.jpg",
        "Chả cá thơm mùi thì là, không bị tanh. Nước mắm pha chuẩn vị Hà Nội.",
        "2024-02-27",
        "24",
        "2",
        "1"),
    DishComment(
        "C024",
        "U024",
        "Trần Thị Xuân",
        "https://randomuser.me/api/portraits/women/12.jpg",
        "Cách ướp cá và xào với thì là rất hay. Màu vàng đẹp mắt, thơm nức.",
        "2024-02-26",
        "19",
        "1",
        "1"),
  ],
  "D013": [
    // Canh chua cá lóc
    DishComment(
        "C025",
        "U025",
        "Lê Văn Yên",
        "https://randomuser.me/api/portraits/men/13.jpg",
        "Canh chua thanh mát, cá không bị tanh. Rau củ giòn ngon.",
        "2024-02-25",
        "16",
        "1",
        "1"),
    DishComment(
        "C026",
        "U026",
        "Hoàng Thị Ánh",
        "https://randomuser.me/api/portraits/women/13.jpg",
        "Vị chua ngọt vừa phải, cá lóc tươi ngon. Công thức rất chuẩn.",
        "2024-02-24",
        "14",
        "0",
        "1"),
  ],
  "D014": [
    // Gà nướng
    DishComment(
        "C027",
        "U027",
        "Phạm Văn Bình",
        "https://randomuser.me/api/portraits/men/14.jpg",
        "Gà nướng thơm mùi sả, da giòn thịt mềm. Cách ướp rất đặc biệt.",
        "2024-02-23",
        "22",
        "1",
        "1"),
    DishComment(
        "C028",
        "U028",
        "Nguyễn Thị Châu",
        "https://randomuser.me/api/portraits/women/14.jpg",
        "Muối ớt chanh ăn kèm rất ngon. Gà nướng không bị khô.",
        "2024-02-22",
        "17",
        "1",
        "1"),
  ],
  "D015": [
    // Bò lúc lắc
    DishComment(
        "C029",
        "U029",
        "Trần Văn Dũng",
        "https://randomuser.me/api/portraits/men/15.jpg",
        "Thịt bò mềm, sốt tiêu đen đậm đà. Cách cắt thịt rất chuẩn.",
        "2024-02-21",
        "20",
        "1",
        "1"),
    DishComment(
        "C030",
        "U030",
        "Lê Thị Em",
        "https://randomuser.me/api/portraits/women/15.jpg",
        "Salad ăn kèm giòn mát. Thịt bò không bị dai, màu đẹp mắt.",
        "2024-02-20",
        "16",
        "0",
        "1"),
  ],
  "D016": [
    // Bánh cuốn
    DishComment(
        "C031",
        "U031",
        "Hoàng Văn Giáp",
        "https://randomuser.me/api/portraits/men/16.jpg",
        "Bánh cuốn mỏng mềm, nhân thịt thơm ngon. Nước chấm đậm đà.",
        "2024-02-19",
        "18",
        "1",
        "1"),
    DishComment(
        "C032",
        "U032",
        "Phạm Thị Hoa",
        "https://randomuser.me/api/portraits/women/16.jpg",
        "Cách tráng bánh rất hay, không bị dính. Hành phi thơm giòn.",
        "2024-02-18",
        "15",
        "0",
        "1"),
  ],
  "D017": [
    // Cơm gà Hải Nam
    DishComment(
        "C033",
        "U033",
        "Nguyễn Văn Hiếu",
        "https://randomuser.me/api/portraits/men/17.jpg",
        "Gà luộc vàng ươm, thịt mềm ngọt. Cơm nấu với nước gà rất thơm.",
        "2024-02-17",
        "23",
        "2",
        "1"),
    DishComment(
        "C034",
        "U034",
        "Trần Thị Hiền",
        "https://randomuser.me/api/portraits/women/17.jpg",
        "Sốt gừng và tương làm rất ngon. Cách luộc gà không bị khô.",
        "2024-02-16",
        "19",
        "1",
        "1"),
  ],
  "D018": [
    // Hủ tiếu Nam Vang
    DishComment(
        "C035",
        "U035",
        "Lê Văn Khoa",
        "https://randomuser.me/api/portraits/men/18.jpg",
        "Nước dùng trong ngọt, hủ tiếu dai ngon. Topping phong phú.",
        "2024-02-15",
        "21",
        "1",
        "1"),
    DishComment(
        "C036",
        "U036",
        "Phạm Thị Linh",
        "https://randomuser.me/api/portraits/women/18.jpg",
        "Tôm thịt tươi ngon, giá đỗ giòn ngọt. Hướng dẫn nấu rất chi tiết.",
        "2024-02-14",
        "17",
        "0",
        "1"),
  ],
  "D019": [
    // Lẩu thái
    DishComment(
        "C037",
        "U037",
        "Hoàng Văn Minh",
        "https://randomuser.me/api/portraits/men/19.jpg",
        "Nước lẩu chua cay đúng vị, hải sản tươi ngon. Rất đầy đủ nguyên liệu.",
        "2024-02-13",
        "25",
        "2",
        "1"),
    DishComment(
        "C038",
        "U038",
        "Nguyễn Thị Mai",
        "https://randomuser.me/api/portraits/women/19.jpg",
        "Cách nấu nước lẩu rất hay, rau nấm đa dạng. Công thức chuẩn vị.",
        "2024-02-12",
        "20",
        "1",
        "1"),
  ],
  "D020": [
    // Mực xào sa tế
    DishComment(
        "C039",
        "U039",
        "Trần Văn Nam",
        "https://randomuser.me/api/portraits/men/20.jpg",
        "Mực tươi ngon, không bị dai. Sa tế đậm đà vừa ăn.",
        "2024-02-11",
        "18",
        "1",
        "1"),
    DishComment(
        "C040",
        "U040",
        "Lê Thị Oanh",
        "https://randomuser.me/api/portraits/women/20.jpg",
        "Mực xào vừa chín tới, không bị khô. Cách ướp rất ngon.",
        "2024-02-10",
        "15",
        "0",
        "1"),
  ],
  "D021": [
    // Cháo lòng
    DishComment(
        "C041",
        "U041",
        "Phan Văn Phúc",
        "https://randomuser.me/api/portraits/men/21.jpg",
        "Cháo nấu nhừ vừa phải, lòng heo sạch và mềm. Hành ngò thơm phức.",
        "2024-02-09",
        "19",
        "1",
        "1"),
    DishComment(
        "C042",
        "U042",
        "Nguyễn Thị Quỳnh",
        "https://randomuser.me/api/portraits/women/21.jpg",
        "Nước dùng ngọt thanh, tiêu hành đủ vị. Cách sơ chế lòng rất kỹ.",
        "2024-02-08",
        "16",
        "0",
        "1"),
  ],
  "D022": [
    // Sườn xào chua ngọt
    DishComment(
        "C043",
        "U043",
        "Trần Văn Rồng",
        "https://randomuser.me/api/portraits/men/22.jpg",
        "Sườn mềm, sốt chua ngọt vừa ăn. Ớt chuông giòn ngọt.",
        "2024-02-07",
        "22",
        "2",
        "1"),
    DishComment(
        "C044",
        "U044",
        "Lê Thị Sen",
        "https://randomuser.me/api/portraits/women/22.jpg",
        "Cách ướp sườn rất ngon, sốt sệt vừa phải. Màu sắc bắt mắt.",
        "2024-02-06",
        "18",
        "1",
        "1"),
  ],
  "D023": [
    // Cá chiên mắm gừng
    DishComment(
        "C045",
        "U045",
        "Hoàng Văn Tâm",
        "https://randomuser.me/api/portraits/men/23.jpg",
        "Cá chiên vàng giòn, sốt mắm gừng đậm đà. Không bị tanh.",
        "2024-02-05",
        "20",
        "1",
        "1"),
    DishComment(
        "C046",
        "U046",
        "Phạm Thị Thanh",
        "https://randomuser.me/api/portraits/women/23.jpg",
        "Mẹo chiên cá không bị dính chảo rất hay. Nước mắm gừng thơm nức.",
        "2024-02-04",
        "17",
        "0",
        "1"),
  ],
  "D024": [
    // Rau muống xào tỏi
    DishComment(
        "C047",
        "U047",
        "Nguyễn Văn Uy",
        "https://randomuser.me/api/portraits/men/24.jpg",
        "Rau muống giòn xanh, tỏi phi thơm vàng. Cách xào giữ được màu rau.",
        "2024-02-03",
        "15",
        "1",
        "1"),
    DishComment(
        "C048",
        "U048",
        "Trần Thị Vân",
        "https://randomuser.me/api/portraits/women/24.jpg",
        "Rau không bị già, tỏi vừa phải. Hướng dẫn chọn rau rất hữu ích.",
        "2024-02-02",
        "12",
        "0",
        "1"),
  ],
  "D025": [
    // Cơm chiên dương châu
    DishComment(
        "C049",
        "U049",
        "Lê Văn Xương",
        "https://randomuser.me/api/portraits/men/25.jpg",
        "Cơm chiên hạt rời, xá xíu thơm ngon. Trứng và tôm đầy đặn.",
        "2024-02-01",
        "24",
        "2",
        "1"),
    DishComment(
        "C050",
        "U050",
        "Phạm Thị Yến",
        "https://randomuser.me/api/portraits/women/25.jpg",
        "Cách chiên cơm không bị dính, nguyên liệu hài hòa. Rất ngon.",
        "2024-01-31",
        "19",
        "1",
        "1"),
  ],
  "D026": [
    // Gỏi đu đủ
    DishComment(
        "C051",
        "U051",
        "Hoàng Văn Zung",
        "https://randomuser.me/api/portraits/men/26.jpg",
        "Đu đủ giòn ngọt, tôm khô thơm béo. Nước trộn vừa vị.",
        "2024-01-30",
        "17",
        "1",
        "1"),
    DishComment(
        "C052",
        "U052",
        "Nguyễn Thị Ánh",
        "https://randomuser.me/api/portraits/women/26.jpg",
        "Cách ngâm đu đủ không bị đắng rất hay. Lạc rang giòn rụm.",
        "2024-01-29",
        "14",
        "0",
        "1"),
  ],
  "D027": [
    // Thịt kho tàu
    DishComment(
        "C053",
        "U053",
        "Trần Văn Bảo",
        "https://randomuser.me/api/portraits/men/27.jpg",
        "Thịt kho mềm, màu đẹp. Trứng thấm vị, nước dừa ngọt thanh.",
        "2024-01-28",
        "23",
        "2",
        "1"),
    DishComment(
        "C054",
        "U054",
        "Lê Thị Cúc",
        "https://randomuser.me/api/portraits/women/27.jpg",
        "Cách kho không bị khô, nước kho sệt vừa phải. Rất ngon cơm.",
        "2024-01-27",
        "18",
        "1",
        "1"),
  ],
  "D028": [
    // Cà ri gà
    DishComment(
        "C055",
        "U055",
        "Phạm Văn Đức",
        "https://randomuser.me/api/portraits/men/28.jpg",
        "Nước cà ri sệt đặc, gà mềm thấm vị. Khoai tây bở ngon.",
        "2024-01-26",
        "21",
        "1",
        "1"),
    DishComment(
        "C056",
        "U056",
        "Hoàng Thị Giang",
        "https://randomuser.me/api/portraits/women/28.jpg",
        "Cách nấu cà ri không bị tanh, màu sắc đẹp mắt. Ăn với bánh mì rất hợp.",
        "2024-01-25",
        "16",
        "0",
        "1"),
  ],
  "D029": [
    // Khổ qua xào trứng
    DishComment(
        "C057",
        "U057",
        "Nguyễn Văn Hải",
        "https://randomuser.me/api/portraits/men/29.jpg",
        "Khổ qua không đắng, trứng béo vừa phải. Món ăn thanh mát.",
        "2024-01-24",
        "15",
        "1",
        "1"),
    DishComment(
        "C058",
        "U058",
        "Trần Thị Hương",
        "https://randomuser.me/api/portraits/women/29.jpg",
        "Cách xào giữ được độ giòn của khổ qua. Trứng không bị khô.",
        "2024-01-23",
        "12",
        "0",
        "1"),
  ],
  "D030": [
    // Canh khổ qua nhồi thịt
    DishComment(
        "C059",
        "U059",
        "Lê Văn Khang",
        "https://randomuser.me/api/portraits/men/30.jpg",
        "Khổ qua nhồi thịt vừa vặn, nước dùng trong ngọt. Thịt mềm ngon.",
        "2024-01-22",
        "20",
        "1",
        "1"),
    DishComment(
        "C060",
        "U060",
        "Phạm Thị Lan",
        "https://randomuser.me/api/portraits/women/30.jpg",
        "Cách nhồi thịt không bị vỡ, khổ qua không đắng. Canh rất thanh mát.",
        "2024-01-21",
        "17",
        "0",
        "1"),
  ],
};

